### ISSUE TITLE
overfitting

### ISSUE THREAD

**Issue by think-chao** [Ien001/non-random-initialization-for-DFL-CNN#3]
Does this project which implement the non-random-initialization helps relieve the over-fitting  problem?

**Comment by think-chao** [comment]
i am working on the Stanford Dog Dataset, training 200 epochs , the top1 and top5 were 100%, but at test, top1 and top5 were 43%, 72%

**Comment by chaerlo** [comment]
@think-chao i meet the same problem, do you solve the problem?

**Comment by think-chao** [comment]
> @think-chao i meet the same problem, do you solve the problem?
